##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## lib/Makefile
##

all:
	$(MAKE_COMMAND) -C my

clean:
	$(MAKE_COMMAND) clean -C my

fclean: clean
	$(MAKE_COMMAND) fclean -C my

re: fclean all
